{{ if .Values.alertmanagerWebhookAdapter.enabled }} 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-webhook-adapter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager-webhook-adapter
    spec:
      containers:
      - name: webhook
        image: {{ .Values.alertmanagerWebhookAdapter.image.repository }}:{{ .Values.alertmanagerWebhookAdapter.image.tag }}
        command:
        - /alertmanager-webhook-adapter
        - --listen-address=:8090
        - --signature=MO-OB
        - --tmpl-lang=zh
        - --tmpl-dir=/alert-templates/
        - --debug=true
        env:
        - name: TZ
          value: Asia/Shanghai
        resources:
          requests:
            memory: 50Mi
            cpu: 100m
          limits:
            memory: 250Mi
            cpu: 500m
        volumeMounts:
          - name: alert-templates
            mountPath: /alert-templates
      volumes:
      - name: alert-templates
        configMap:
          name: alert-template-config-map
      restartPolicy: Always
      {{ with .Values.alertmanagerWebhookAdapter.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.alertmanagerWebhookAdapter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.alertmanagerWebhookAdapter.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}

{{ end }}