apiVersion: v2
name: mo-ob-private
description: mo-ob-private's Helm chart for Kubernetes
type: application
version: 1.0.0-alpha
appVersion: 0.9.0
dependencies:
- condition: mo-ob-opensource.enabled
  name: mo-ob-opensource
  repository: https://matrixone-cloud.github.io/observability
  version: 1.0.0-alpha.16
- condition: mo-ruler-stack.enabled
  name: mo-ruler-stack
  repository: https://matrixone-cloud.github.io/observability
  version: 1.0.0-alpha.13

