global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  # - job_name: "node"
  #   static_configs:
  #   - targets: ["node-exporter:9100"]
  
  - job_name: 'demo'
    static_configs:
      - targets:
        - 'demo.promlabs.com:10000'
        - 'demo.promlabs.com:10001'
        - 'demo.promlabs.com:10002'

remote_write:
  - url: "http://mo-agent:8000/v1/metrics"