{{- if .Values.alertrules.enabled }}
## cooperate with {folder_to_char}/alert-rules/log-alert-rules/*.yaml
{{- $files := .Files.Glob "alert-rules/log-alert-rules/*.yaml" }}
{{- if $files }}
apiVersion: v1
kind: ConfigMapList
items:
{{- range $path, $fileContents := $files }}
{{- $alertFileName := regexReplaceAll "(^.*/)(.*/)(.*)\\.yaml$" $path "${3}" }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: {{ $.Values.alerting.namespace }}
    name: {{ printf "%s" $alertFileName | trunc 63 | trimSuffix "-" }}
    labels:
      app: "mo-ruler-stack"
      loki_rule: "true"
  data:
   {{ printf "%s.yaml" $alertFileName }}: {{ $.Files.Get $path | toYaml | indent 2}}
{{- end }}
{{- end }}
{{- end }} # end if enabled
