name: Chart Release Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main,'[0-9]+.[0-9]+.[0-9]+' ]
    paths:
    - 'charts/**'

permissions: read-all

jobs:
  release_check:
    permissions:
      contents: write # for helm/chart-releaser-action to push chart release and create a release
    runs-on: amd64-moc-guangzhou-medium8

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Copy rules file for ob-opensource
        run: |
          cp -r ./charts/mo-ruler-stack/rules ./charts/mo-ob-opensource/rules

      - name: Run Artifact Hub lint
        run: |
          #curl -s https://api.github.com/repos/artifacthub/hub/releases/latest | grep -E 'browser_download_url' | grep linux_amd64.tar.gz\" | grep -Eo 'https://[^\"]*' | xargs wget -O - | tar -xz
          echo "https://github.com/artifacthub/hub/releases/download/v1.16.0/ah_1.16.0_linux_amd64.tar.gz" | xargs wget -O - | tar -xz
          ./ah lint -p charts || exit 1
          rm -f ./ah
