name: Build Docker Image (echo-server)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image, use v1.0 if empty'
        default: 'v1.0'
        required: false
        type: string

jobs:
  docker:
    runs-on: amd64-tke-dind
    steps:

      - uses: actions/checkout@v3

      - name: Print Current Image Tags
        run: |
          echo "Current Last 30 Tags:"
          wget -q -O - "https://hub.docker.com/v2/namespaces/matrixorigin/repositories/observability/tags?page_size=30" | grep -o '"name": *"[^"]*' | grep -o '[^"]*$'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Echo Server
        uses: docker/build-push-action@v4
        with:
          # 解决私有仓库拉取问题
          build-args: |
            GITHUB_ACCESS_TOKEN=${{ secrets.TOKEN_ACTION }}
          file: ./.github/observability/check-alertmanager/echo-server/Dockerfile
          context: ./.github/observability/check-alertmanager/echo-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: matrixorigin/observability:echo-server-${{ inputs.tag }}

      - name: Print Latest Image Tags
        run: |
          echo "Latest Last 30 Tags:"
          wget -q -O - "https://hub.docker.com/v2/namespaces/matrixorigin/repositories/observability/tags?page_size=30" | grep -o '"name": *"[^"]*' | grep -o '[^"]*$'
