name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Add Label by files changed
      # more details in https://github.com/actions/labeler
      ## rely on .github/labeler.yml
      uses: actions/labeler@v4
